// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYK_bexy8y2GHbjn8jfD0EVYeF_nQdcFo',
    appId: '1:68013423242:web:191249b80740427f664b73',
    messagingSenderId: '68013423242',
    projectId: 'globalin-project',
    authDomain: 'globalin-project.firebaseapp.com',
    storageBucket: 'globalin-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIlHUxeyLgTdLk8DGIpJ-ZwrxY1ej8Q8',
    appId: '1:68013423242:android:a27a063184f27898664b73',
    messagingSenderId: '68013423242',
    projectId: 'globalin-project',
    storageBucket: 'globalin-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMcuOs9qMYPeJis8Itx26il4Ff8ZoaGxM',
    appId: '1:68013423242:ios:248f02edddf62ac2664b73',
    messagingSenderId: '68013423242',
    projectId: 'globalin-project',
    storageBucket: 'globalin-project.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );
}
